"""added venues

Revision ID: 9836338835c6
Revises: c95f8452ebc1
Create Date: 2024-12-04 13:59:34.031254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9836338835c6'
down_revision = 'c95f8452ebc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_capacity'), ['capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_name'), ['name'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_events_venue_id_venues'), 'venues', ['venue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_venue_id_venues'), type_='foreignkey')
        batch_op.drop_column('venue_id')

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_name'))
        batch_op.drop_index(batch_op.f('ix_venues_location'))
        batch_op.drop_index(batch_op.f('ix_venues_description'))
        batch_op.drop_index(batch_op.f('ix_venues_capacity'))

    op.drop_table('venues')
    # ### end Alembic commands ###
