"""added image_url to events

Revision ID: ad11fe598375
Revises: a41e4197edc7
Create Date: 2025-01-28 10:50:42.393069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad11fe598375'
down_revision = 'a41e4197edc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=False, server_default='default_image_url'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events') as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
