"""updated event

Revision ID: c5de2288833f
Revises: cc4c92f8c444
Create Date: 2025-02-13 22:44:51.914377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5de2288833f'
down_revision = 'cc4c92f8c444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_capacity')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_events_capacity', ['capacity'], unique=False)

    # ### end Alembic commands ###
