"""added start time to events

Revision ID: c95f8452ebc1
Revises: dd05c1938740
Create Date: 2024-12-03 10:18:41.593077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95f8452ebc1'
down_revision = 'dd05c1938740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_events_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start_time'))
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
